Repository medInria/medInria-public, pull requests merged in 2019-11, with the labels that each got.

#451 [Splash] solve corner transparency pb, change logo
  src/app/medInria/main.cpp
  src/app/medInria/medSplashScreen.cpp
Labels: Minor bug, enhancement

#485 [JSON] Registration workspace and polygonROI
  src/plugins/legacy/medRegistrationWorkspace/medRegistrationWorkspacePlugin.json
  src/plugins/legacy/medVtkView/medVtkViewPlugin.json
  src/plugins/legacy/polygonRoi/polygonRoiPlugin.json
Labels: Minor bug

#482 [IDE] display html files
  src/app/medInria/CMakeLists.txt
  src/app/medInria/resources/CMakeLists.txt
  src/cmake/module/list_source_files.cmake
Labels: Enhancement

#478 [qRegisterMetaType] clean qt metatype register at app opening
  src/app/medInria/main.cpp
  src/app/medInria/medApplication.cpp
Labels: Enhancement

#497 [DB] solve temporary index removal
  src/layers/legacy/medCoreLegacy/database/medDatabaseModel.cpp
  src/layers/legacy/medCoreLegacy/database/medDatabaseNonPersistentController.cpp
Labels: Major bug

#501 Correction of a big part for memory issues
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.cxx
Labels: Critical bug

#499 [Documentation] update readme
  README.md
Labels: Enhancement

#505 [Warnings] remove a lot of medInria warnings
  src/app/medInria/areas/workspaces/filtering/medFilteringWorkspace.cpp
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.cxx
  src/plugins/legacy/itkDataSHImage/management/vtkSphericalHarmonicSource.cxx
  src/plugins/process/bias_correction/medItkBiasCorrectionProcess.cpp
  src/plugins/process/mask_image/medItkMaskImageProcess.cpp
  superbuild/projects_modules/medInria.cmake
Labels: Minor bug

#506 [DB] save-on-quit save temporary data: no duplicated names
  src/layers/legacy/medCoreLegacy/database/medAbstractDatabaseImporter.cpp
Labels: Major bug

#507 [Composer] menu become QtoolButton, not application menubar
  src/app/medInria/areas/composer/medComposerArea.cpp
Labels: Major bug

#510 [Run] avoid debug warning at app launch
  src/app/medInria/main.cpp
Labels: Minor bug
