Repository medInria/medInria-public, pull requests merged in 2019-12, with the labels that each got.

#516 Fix #494 Bad center or rotation for the 3D view with (some) vector image
  src/plugins/legacy/medVtkView/medVtkViewNavigator.cpp
Labels: Critical bug

#513 [Reslice] solve crash using reslice toolbox
  src/plugins/legacy/reformat/medResliceViewer.cpp
  src/plugins/legacy/reformat/medResliceViewer.h
  src/plugins/legacy/reformat/resliceToolBox.cpp
Labels: Major bug

#519 [SearchToolbox] open at app start on some pc
  src/app/medInria/medQuickAccessMenu.cpp
Labels: Minor bug

#521 [Ubuntu 16]: add missing include in medImageMaskAnnotationData
  src/layers/legacy/medCoreLegacy/data/annotationData/medImageMaskAnnotationData.cpp
Labels: Minor bug

#518 [DataInteractor] min/max intensities steps
  src/layers/legacy/medCoreLegacy/parameters/medDoubleParameterL.cpp
  src/layers/legacy/medCoreLegacy/parameters/medDoubleParameterL.h
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView.cxx
  src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImageInteractor.cpp
Labels: Minor bug

#520 [DB] avoid not-found saved data in a new database after restart
  src/layers/legacy/medCoreLegacy/database/medDatabaseController.cpp
  src/layers/legacy/medCoreLegacy/database/medDatabaseReader.cpp
Labels: Major bug
