Repository medInria/medInria-public, pull requests merged in 2019-10, with the labels that each got.

#395 [music3] add a pop-up to validate exit
  src/app/medInria/medMainWindow.cpp
  src/app/medInria/medMainWindow.h
Labels: enhancement

#396 [music3] disable lighting for meshes in 2D
  src/layers/legacy/medCoreLegacy/data/medAbstractData.cpp
  src/layers/legacy/medCoreLegacy/data/medAbstractData.h
  src/layers/legacy/medVtkDataMeshBase/CMakeLists.txt
  src/plugins/legacy/vtkDataMesh/interactors/vtkDataMeshInteractor.cpp
Labels: Minor bug, enhancement

#404 [music3] Reset camera on layer double click
  src/layers/legacy/medCoreLegacy/gui/medAbstractWorkspaceLegacy.cpp
  src/layers/legacy/medCoreLegacy/gui/medAbstractWorkspaceLegacy.h
  src/layers/legacy/medCoreLegacy/views/medAbstractLayeredView.cpp
  src/layers/legacy/medCoreLegacy/views/medAbstractLayeredView.h
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView.cxx
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView.h
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView2D.cxx
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView2D.h
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.cxx
  src/plugins/legacy/medVtkView/CMakeLists.txt
  src/plugins/legacy/medVtkView/medVtkView.cpp
  src/plugins/legacy/medVtkView/medVtkView.h
Labels: enhancement

#397 [music3] medUtilities empty variable crash solved
  src/layers/legacy/medUtilities/medUtilities.cpp
Labels: Major bug

#400 [music3] generateThumbnail - remove pop-up at import in DB
  src/layers/legacy/medCoreLegacy/data/medAbstractData.cpp
Labels: Minor bug

#401 [music3] in Browser/File System path saved
  src/app/medInria/medFileSystemDataSource.cpp
Labels: enhancement

#402 [music3] change the background color - kept in screenshots
  src/app/medInria/medMainWindow.cpp
  src/plugins/legacy/vtkDataMesh/navigators/vtkDataMeshNavigator.cpp
  src/plugins/legacy/vtkDataMesh/navigators/vtkDataMeshNavigator.h
Labels: enhancement

#405 [music3] add method to retrieve a specific layer interactor
  src/layers/legacy/medCoreLegacy/views/medAbstractLayeredView.h
Labels: enhancement

#411 [music3] medAbstractLayeredView - Fix add data twice
  src/layers/legacy/medCoreLegacy/views/medAbstractLayeredView.cpp
Labels: Minor bug

#416 [music3] medVtkViewItkDataImageInteractor - fixes scroll bug in 4-window view
  src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImageInteractor.cpp
Labels: Major bug

#431 [Import] clean logs during dicom import
  src/layers/legacy/medCoreLegacy/database/medAbstractDatabaseImporter.cpp
  src/layers/legacy/medCoreLegacy/gui/viewContainers/medViewContainer.cpp
  src/layers/legacy/medImageIO/itkDCMTKImageIO.cpp
  src/plugins/legacy/itkDataImage/readers/itkDCMTKDataImageReader.cpp
  superbuild/patches/DCMTK_STL_QUIET.patch
  superbuild/projects_modules/DCMTK.cmake
Labels: Major bug, enhancement

#403 [music3] four-split and maximized actions menu cleaned
  src/app/medInria/resources/medInria.qss
  src/layers/legacy/medCoreLegacy/gui/viewContainers/medViewContainer.cpp
  src/layers/legacy/medCoreLegacy/gui/viewContainers/medViewContainer.h
  src/layers/legacy/medCoreLegacy/views/medAbstractImageView.cpp
  src/layers/legacy/medCoreLegacy/views/medAbstractImageView.h
Labels: Major bug, enhancement

#426 [music3] Voi Cutter - add toolbox
  src/layers/legacy/medCoreLegacy/parameters/medBoolGroupParameterL.h
  src/plugins/CMakeLists.txt
  src/plugins/legacy/voiCutter/CMakeLists.txt
  src/plugins/legacy/voiCutter/voiCutterPlugin.cpp
  src/plugins/legacy/voiCutter/voiCutterPlugin.h
  src/plugins/legacy/voiCutter/voiCutterPlugin.json
  src/plugins/legacy/voiCutter/voiCutterPluginExport.h
  src/plugins/legacy/voiCutter/voiCutterToolBox.cpp
  src/plugins/legacy/voiCutter/voiCutterToolBox.h
  src/plugins/legacy/voiCutter/vtkInriaInteractorStyleDrawPolygon.cxx
  src/plugins/legacy/voiCutter/vtkInriaInteractorStyleDrawPolygon.h
Labels: enhancement

#415 [music3] DB - open a study with several series in a view
  src/layers/legacy/medCoreLegacy/database/medDatabaseModel.cpp
  src/layers/legacy/medCoreLegacy/gui/database/medDatabaseView.cpp
  src/layers/legacy/medCoreLegacy/gui/medAbstractWorkspaceLegacy.cpp
  src/layers/legacy/medCoreLegacy/gui/viewContainers/medViewContainer.cpp
  src/layers/legacy/medCoreLegacy/gui/viewContainers/medViewContainer.h
Labels: enhancement

#428 [music3] Meshing Workspace + 4 toolboxes
  src/layers/legacy/medCoreLegacy/database/medDataManager.cpp
  src/layers/legacy/medCoreLegacy/gui/commonWidgets/medComboBox.h
  src/layers/legacy/medCoreLegacy/gui/database/medDatabaseView.cpp
  src/layers/legacy/medCoreLegacy/gui/toolboxes/medSelectorToolBox.cpp
  src/layers/legacy/medCoreLegacy/gui/toolboxes/medSelectorToolBox.h
  src/layers/legacy/medCoreLegacy/gui/viewContainers/medViewContainer.cpp
  src/layers/legacy/medCoreLegacy/medMessageController.cpp
  src/layers/legacy/medVtkDataMeshBase/vtkMetaDataSet.cxx
  src/plugins/CMakeLists.txt
  src/plugins/legacy/manualRegistration/manualRegistrationToolBox.h
  src/plugins/legacy/medCreateMeshFromMask/CMakeLists.txt
  src/plugins/legacy/medCreateMeshFromMask/medCreateMeshFromMask.cpp
  src/plugins/legacy/medCreateMeshFromMask/medCreateMeshFromMask.h
  src/plugins/legacy/medCreateMeshFromMask/medCreateMeshFromMaskPlugin.cpp
  src/plugins/legacy/medCreateMeshFromMask/medCreateMeshFromMaskPlugin.h
  src/plugins/legacy/medCreateMeshFromMask/medCreateMeshFromMaskPlugin.json
  src/plugins/legacy/medCreateMeshFromMask/medCreateMeshFromMaskPluginExport.h
  src/plugins/legacy/medCreateMeshFromMask/medCreateMeshFromMaskToolBox.cpp
  src/plugins/legacy/medCreateMeshFromMask/medCreateMeshFromMaskToolBox.h
  src/plugins/legacy/medMeshingWorkspace/CMakeLists.txt
  src/plugins/legacy/medMeshingWorkspace/medMeshingWorkspace.cpp
  src/plugins/legacy/medMeshingWorkspace/medMeshingWorkspace.h
  src/plugins/legacy/medMeshingWorkspace/medMeshingWorkspacePlugin.cpp
  src/plugins/legacy/medMeshingWorkspace/medMeshingWorkspacePlugin.h
  src/plugins/legacy/medMeshingWorkspace/medMeshingWorkspacePlugin.json
  src/plugins/legacy/medMeshingWorkspace/medMeshingWorkspacePluginExport.h
  src/plugins/legacy/medRemeshing/CMakeLists.txt
  src/plugins/legacy/medRemeshing/medDecimateMeshProcess.cpp
  src/plugins/legacy/medRemeshing/medDecimateMeshProcess.h
  src/plugins/legacy/medRemeshing/medRefineMeshProcess.cpp
  src/plugins/legacy/medRemeshing/medRefineMeshProcess.h
  src/plugins/legacy/medRemeshing/medRemeshingPlugin.cpp
  src/plugins/legacy/medRemeshing/medRemeshingPlugin.h
  src/plugins/legacy/medRemeshing/medRemeshingPlugin.json
  src/plugins/legacy/medRemeshing/medRemeshingPluginExport.h
  src/plugins/legacy/medRemeshing/medRemeshingToolBox.cpp
  src/plugins/legacy/medRemeshing/medRemeshingToolBox.h
  src/plugins/legacy/medRemeshing/medSmoothMeshProcess.cpp
  src/plugins/legacy/medRemeshing/medSmoothMeshProcess.h
  src/plugins/legacy/medVtkView/medVtkViewNavigator.cpp
  src/plugins/legacy/meshManipulation/CMakeLists.txt
  src/plugins/legacy/meshManipulation/meshManipulationPlugin.cpp
  src/plugins/legacy/meshManipulation/meshManipulationPlugin.h
  src/plugins/legacy/meshManipulation/meshManipulationPlugin.json
  src/plugins/legacy/meshManipulation/meshManipulationPluginExport.h
  src/plugins/legacy/meshManipulation/meshManipulationToolBox.cpp
  src/plugins/legacy/meshManipulation/meshManipulationToolBox.h
  src/plugins/legacy/meshMapping/CMakeLists.txt
  src/plugins/legacy/meshMapping/meshMapping.cpp
  src/plugins/legacy/meshMapping/meshMapping.h
  src/plugins/legacy/meshMapping/meshMappingPlugin.cpp
  src/plugins/legacy/meshMapping/meshMappingPlugin.h
  src/plugins/legacy/meshMapping/meshMappingPlugin.json
  src/plugins/legacy/meshMapping/meshMappingPluginExport.h
  src/plugins/legacy/meshMapping/meshMappingToolBox.cpp
  src/plugins/legacy/meshMapping/meshMappingToolBox.h
  src/plugins/legacy/vtkDataMesh/interactors/vtkDataMeshInteractor.cpp
Labels: Minor bug, enhancement

#434 [medComboBox] add a doxygen description
  src/layers/legacy/medCoreLegacy/gui/commonWidgets/medComboBox.h
Labels: enhancement

#435 [CMakeLists] add required components
  src/plugins/legacy/itkProcessRegistrationDiffeomorphicDemons/CMakeLists.txt
  src/plugins/legacy/manualRegistration/CMakeLists.txt
  src/plugins/legacy/medAlgorithmPaint/CMakeLists.txt
  src/plugins/legacy/medBinaryOperation/CMakeLists.txt
  src/plugins/legacy/medCreateMeshFromMask/CMakeLists.txt
  src/plugins/legacy/medMaskApplication/CMakeLists.txt
  src/plugins/legacy/medRemeshing/CMakeLists.txt
  src/plugins/legacy/meshManipulation/CMakeLists.txt
  src/plugins/legacy/meshMapping/CMakeLists.txt
  src/plugins/legacy/polygonRoi/CMakeLists.txt
  src/plugins/legacy/reformat/CMakeLists.txt
  src/plugins/legacy/variationalSegmentation/CMakeLists.txt
  src/plugins/legacy/voiCutter/CMakeLists.txt
Labels: enhancement

#453 [DICOM] import non axial acquisition
  src/layers/legacy/medImageIO/itkDCMTKImageIO.cpp
Labels: Major bug

#458 [4-split] bug with the slice parameter
  src/layers/legacy/medCoreLegacy/views/medAbstractImageView.cpp
Labels: Major bug

#457 [Maximize] rebase error maximize action disappear
  src/layers/legacy/medCoreLegacy/gui/viewContainers/medViewContainer.cpp
Labels: Major bug

#443 [Authors] add music dev to author list
  src/app/medInria/resources/authors.html
Labels: enhancement

#447 [music3] add Iterative Closest Point tlbx
  src/layers/legacy/medVtkDataMeshBase/vtkMetaSurfaceMesh.cxx
  src/layers/legacy/medVtkDataMeshBase/vtkMetaVolumeMesh.cxx
  src/plugins/CMakeLists.txt
  src/plugins/legacy/iterativeClosestPoint/CMakeLists.txt
  src/plugins/legacy/iterativeClosestPoint/iterativeClosestPointPlugin.cpp
  src/plugins/legacy/iterativeClosestPoint/iterativeClosestPointPlugin.h
  src/plugins/legacy/iterativeClosestPoint/iterativeClosestPointPlugin.json
  src/plugins/legacy/iterativeClosestPoint/iterativeClosestPointPluginExport.h
  src/plugins/legacy/iterativeClosestPoint/iterativeClosestPointProcess.cpp
  src/plugins/legacy/iterativeClosestPoint/iterativeClosestPointProcess.h
  src/plugins/legacy/iterativeClosestPoint/iterativeClosestPointToolBox.cpp
  src/plugins/legacy/iterativeClosestPoint/iterativeClosestPointToolBox.h
  src/plugins/legacy/iterativeClosestPoint/vtkICPFilter.cxx
  src/plugins/legacy/iterativeClosestPoint/vtkICPFilter.h
Labels: enhancement

#450 [Logos] adjust-containers logo disabled
  src/app/medInria/medMainWindow.cpp
  src/app/medInria/resources/icons/adjust_size.png
  src/app/medInria/resources/icons/adjust_size_grey.png
  src/app/medInria/resources/medInria.qrc
Labels: Minor bug

#455 [Diffeomorphic] shorten plugin name
  src/plugins/CMakeLists.txt
  src/plugins/legacy/diffeomorphicDemons/CMakeLists.txt
  src/plugins/legacy/diffeomorphicDemons/diffeomorphicDemons.cpp
  src/plugins/legacy/diffeomorphicDemons/diffeomorphicDemons.h
  src/plugins/legacy/diffeomorphicDemons/diffeomorphicDemonsPlugin.cpp
  src/plugins/legacy/diffeomorphicDemons/diffeomorphicDemonsPlugin.h
  src/plugins/legacy/diffeomorphicDemons/diffeomorphicDemonsPlugin.json
  src/plugins/legacy/diffeomorphicDemons/diffeomorphicDemonsPluginExport.h
  src/plugins/legacy/diffeomorphicDemons/diffeomorphicDemonsToolBox.cpp
  src/plugins/legacy/diffeomorphicDemons/diffeomorphicDemonsToolBox.h
  src/plugins/legacy/itkProcessRegistrationDiffeomorphicDemons/itkProcessRegistrationDiffeomorphicDemonsPlugin.cpp
Labels: enhancement

#456 [vtk-ish files] opacity and color for some file types
  src/plugins/legacy/vtkDataMesh/interactors/vtkDataMeshInteractor.cpp
Labels: enhancement

#459 [PolygonROI] crash delete roi and switch to other tlbx
  src/plugins/legacy/polygonRoi/polygonRoiToolBox.cpp
Labels: Major bug

#462 [ManualRegistration] compilation error with itkTransformIOFactoryRegi…
  src/plugins/legacy/manualRegistration/CMakeLists.txt
Labels: Critical bug

#461 [medAbstractDataWriter] add files to export list of data
  src/layers/legacy/medCoreLegacy/data/medAbstractDataWriter.cpp
  src/layers/legacy/medCoreLegacy/data/medAbstractDataWriter.h
Labels: enhancement

#465 [diffeo] right name in json
  src/plugins/legacy/diffeomorphicDemons/diffeomorphicDemonsPlugin.json
Labels: Major bug

#467 [N4Bias] Filtering tlbx medN4BiasCorrection added
  src/plugins/CMakeLists.txt
  src/plugins/legacy/medN4BiasCorrection/CMakeLists.txt
  src/plugins/legacy/medN4BiasCorrection/medN4BiasCorrection.cpp
  src/plugins/legacy/medN4BiasCorrection/medN4BiasCorrection.h
  src/plugins/legacy/medN4BiasCorrection/medN4BiasCorrectionPlugin.cpp
  src/plugins/legacy/medN4BiasCorrection/medN4BiasCorrectionPlugin.h
  src/plugins/legacy/medN4BiasCorrection/medN4BiasCorrectionPlugin.json
  src/plugins/legacy/medN4BiasCorrection/medN4BiasCorrectionPluginExport.h
  src/plugins/legacy/medN4BiasCorrection/medN4BiasCorrectionToolBox.cpp
  src/plugins/legacy/medN4BiasCorrection/medN4BiasCorrectionToolBox.h
  src/plugins/legacy/medN4BiasCorrection/medN4BiasCorrection_p.h
Labels: enhancement

#466 [diffeo] standardize export file for windows
  src/plugins/legacy/diffeomorphicDemons/diffeomorphicDemonsPlugin.h
  src/plugins/legacy/diffeomorphicDemons/diffeomorphicDemonsPluginExport.h
Labels: Minor bug

#464 [itkFilters] add plugin in Filtering
  src/plugins/CMakeLists.txt
  src/plugins/legacy/itkFilters/CMakeLists.txt
  src/plugins/legacy/itkFilters/itkFiltersAddProcess.cpp
  src/plugins/legacy/itkFilters/itkFiltersAddProcess.h
  src/plugins/legacy/itkFilters/itkFiltersBinaryCloseProcess.cpp
  src/plugins/legacy/itkFilters/itkFiltersBinaryCloseProcess.h
  src/plugins/legacy/itkFilters/itkFiltersBinaryOpenProcess.cpp
  src/plugins/legacy/itkFilters/itkFiltersBinaryOpenProcess.h
  src/plugins/legacy/itkFilters/itkFiltersBinaryThresholdingProcess.cpp
  src/plugins/legacy/itkFilters/itkFiltersBinaryThresholdingProcess.h
  src/plugins/legacy/itkFilters/itkFiltersComponentSizeThresholdProcess.cpp
  src/plugins/legacy/itkFilters/itkFiltersComponentSizeThresholdProcess.h
  src/plugins/legacy/itkFilters/itkFiltersDilateProcess.cpp
  src/plugins/legacy/itkFilters/itkFiltersDilateProcess.h
  src/plugins/legacy/itkFilters/itkFiltersDivideProcess.cpp
  src/plugins/legacy/itkFilters/itkFiltersDivideProcess.h
  src/plugins/legacy/itkFilters/itkFiltersErodeProcess.cpp
  src/plugins/legacy/itkFilters/itkFiltersErodeProcess.h
  src/plugins/legacy/itkFilters/itkFiltersGaussianProcess.cpp
  src/plugins/legacy/itkFilters/itkFiltersGaussianProcess.h
  src/plugins/legacy/itkFilters/itkFiltersGrayscaleCloseProcess.cpp
  src/plugins/legacy/itkFilters/itkFiltersGrayscaleCloseProcess.h
  src/plugins/legacy/itkFilters/itkFiltersGrayscaleOpenProcess.cpp
  src/plugins/legacy/itkFilters/itkFiltersGrayscaleOpenProcess.h
  src/plugins/legacy/itkFilters/itkFiltersInvertProcess.cpp
  src/plugins/legacy/itkFilters/itkFiltersInvertProcess.h
  src/plugins/legacy/itkFilters/itkFiltersMedianProcess.cpp
  src/plugins/legacy/itkFilters/itkFiltersMedianProcess.h
  src/plugins/legacy/itkFilters/itkFiltersMultiplyProcess.cpp
  src/plugins/legacy/itkFilters/itkFiltersMultiplyProcess.h
  src/plugins/legacy/itkFilters/itkFiltersNormalizeProcess.cpp
  src/plugins/legacy/itkFilters/itkFiltersNormalizeProcess.h
  src/plugins/legacy/itkFilters/itkFiltersPlugin.cpp
  src/plugins/legacy/itkFilters/itkFiltersPlugin.h
  src/plugins/legacy/itkFilters/itkFiltersPlugin.json
  src/plugins/legacy/itkFilters/itkFiltersPluginExport.h
  src/plugins/legacy/itkFilters/itkFiltersProcessBase.cpp
  src/plugins/legacy/itkFilters/itkFiltersProcessBase.h
  src/plugins/legacy/itkFilters/itkFiltersShrinkProcess.cpp
  src/plugins/legacy/itkFilters/itkFiltersShrinkProcess.h
  src/plugins/legacy/itkFilters/itkFiltersSubtractProcess.cpp
  src/plugins/legacy/itkFilters/itkFiltersSubtractProcess.h
  src/plugins/legacy/itkFilters/itkFiltersThresholdingProcess.cpp
  src/plugins/legacy/itkFilters/itkFiltersThresholdingProcess.h
  src/plugins/legacy/itkFilters/itkFiltersToolBox.cpp
  src/plugins/legacy/itkFilters/itkFiltersToolBox.h
  src/plugins/legacy/itkFilters/itkFiltersWindowingProcess.cpp
  src/plugins/legacy/itkFilters/itkFiltersWindowingProcess.h
  src/plugins/legacy/itkFilters/itkMorphologicalFiltersProcessBase.cpp
  src/plugins/legacy/itkFilters/itkMorphologicalFiltersProcessBase.h
  src/plugins/legacy/itkFilters/itkMorphologicalFiltersToolBox.cpp
  src/plugins/legacy/itkFilters/itkMorphologicalFiltersToolBox.h
Labels: enhancement

#469 [MACOSX - FIX] - medN4BiasCorrection - build and link errors
  src/plugins/legacy/medN4BiasCorrection/CMakeLists.txt
  src/plugins/legacy/medN4BiasCorrection/medN4BiasCorrectionToolBox.cpp
Labels: Minor bug

#476 [Import] data without name get filename
  src/layers/legacy/medCoreLegacy/database/medAbstractDatabaseImporter.cpp
  src/layers/legacy/medCoreLegacy/database/medDatabaseImporter.cpp
  src/layers/legacy/medCoreLegacy/database/medDatabaseNonPersistentImporter.cpp
Labels: Minor bug

#475 [VariationalSeg] interactors cleaning
  src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImage4DInteractor.cpp
  src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImageInteractor.cpp
  src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImageInteractor.h
  src/plugins/legacy/variationalSegmentation/varSegToolBox.cpp
  src/plugins/legacy/vtkDataMesh/interactors/vtkDataMeshInteractor.cpp
Labels: Critical bug
