Repository medInria/medInria-public, pull requests merged in 2020-02, with the labels that each got.

#546 [nullptr] small typo
  src/layers/legacy/medCoreLegacy/gui/toolboxes/medToolBoxTab.cpp
Labels: Minor bug

#537 [Deprecated] qSort -> std::sort
  src/layers/legacy/medCoreLegacy/data/annotationData/medImageMaskAnnotationData.cpp
  src/layers/legacy/medCoreLegacy/gui/database/medDatabasePreview.cpp
  src/layers/legacy/medCoreLegacy/gui/factories/medWorkspaceFactory.cpp
  src/layers/legacy/medCoreLegacy/gui/lookUpTables/medClutEditor.cpp
  src/layers/legacy/medCoreLegacy/gui/toolboxes/medSelectorToolBox.cpp
  src/layers/legacy/medTest/medQtDataImageWriter.cpp
  src/plugins/legacy/medVtkFibersData/interactors/medVtkFibersDataInteractor.cpp
  src/plugins/legacy/polygonRoi/medRoiManager.cpp
  src/plugins/legacy/polygonRoi/vtkInriaInteractorStylePolygonRepulsor.cxx
Labels: Enhancement

#539 Viewer optimization v4.0
  src/layers/legacy/medImageIO/vtkItkConversion.tpp
  src/layers/legacy/medVtkInria/vtkImageView/vtkImage2DDisplay.cpp
  src/layers/legacy/medVtkInria/vtkImageView/vtkImage2DDisplay.h
  src/layers/legacy/medVtkInria/vtkImageView/vtkImage3DDisplay.cpp
  src/layers/legacy/medVtkInria/vtkImageView/vtkImage3DDisplay.h
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView.cxx
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView.h
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView2D.cxx
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView2D.h
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.cxx
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.h
  src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImageInteractor.cpp
Labels: Enhancement

#550 [3.1.1] window/level lag + annotatedCube + annotation layer + createSeriesTable return
  src/layers/legacy/medCoreLegacy/database/medDatabaseController.cpp
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView.cxx
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView2D.cxx
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView2D.h
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView2DCommand.cxx
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.cxx
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.h
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageViewCornerAnnotation.cxx
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageViewCornerAnnotation.h
  src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImageInteractor.cpp
  src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImageInteractor.h
Labels: Major bug
