Repository medInria/medInria-public, pull requests merged in 2020-10, with the labels that each got.

#773 [VTK] update patch with QPainterPath
  superbuild/patches/VTK.patch
Labels: Major bug

#766 [ReleaseNotes] add 3.2 additions/changes/debug
  RELEASE_NOTES.txt
Labels: Enhancement

#774 [ExternalProjects] avoid duplication with dtkImaging
  superbuild/CMakeLists.txt
Labels: Enhancement

#776 Improve find_program bash
  superbuild/external_projects_tools/EP_CheckEnvironment.cmake
Labels: Enhancement

#779 Forgotten plugins
  src/plugins/CMakeLists.txt
  src/plugins/legacy/itkProcessRegistrationOptimus/CMakeLists.txt
  src/plugins/legacy/itkProcessRegistrationOptimus/itkNewUoaOptimizer.cpp
  src/plugins/legacy/itkProcessRegistrationOptimus/itkNewUoaOptimizer.h
  src/plugins/legacy/itkProcessRegistrationOptimus/itkProcessRegistrationOptimus.cpp
  src/plugins/legacy/itkProcessRegistrationOptimus/itkProcessRegistrationOptimus.h
  src/plugins/legacy/itkProcessRegistrationOptimus/itkProcessRegistrationOptimusPlugin.cpp
  src/plugins/legacy/itkProcessRegistrationOptimus/itkProcessRegistrationOptimusPlugin.h
  src/plugins/legacy/itkProcessRegistrationOptimus/itkProcessRegistrationOptimusPlugin.json
  src/plugins/legacy/itkProcessRegistrationOptimus/itkProcessRegistrationOptimusPluginExport.h
  src/plugins/legacy/itkProcessRegistrationOptimus/itkProcessRegistrationOptimusToolBox.cpp
  src/plugins/legacy/itkProcessRegistrationOptimus/itkProcessRegistrationOptimusToolBox.h
  src/plugins/legacy/itkProcessRegistrationOptimus/rpiOptimus.h
  src/plugins/legacy/itkProcessRegistrationOptimus/rpiOptimus.tpp
  src/plugins/process/dwi_basic_thresholding/CMakeLists.txt
  src/plugins/process/itkDWIBrainMaskCalculatorProcess/CMakeLists.txt
  src/plugins/process/itkDWIBrainMaskCalculatorProcess/itkDWIBrainMaskCalculatorProcess.cpp
  src/plugins/process/itkDWIBrainMaskCalculatorProcess/itkDWIBrainMaskCalculatorProcess.h
  src/plugins/process/itkDWIBrainMaskCalculatorProcess/itkDWIBrainMaskCalculatorProcessPlugin.cpp
  src/plugins/process/itkDWIBrainMaskCalculatorProcess/itkDWIBrainMaskCalculatorProcessPlugin.h
  src/plugins/process/itkDWIBrainMaskCalculatorProcess/itkDWIBrainMaskCalculatorProcessPlugin.json
  src/plugins/process/itkDWIBrainMaskCalculatorProcess/itkDWIBrainMaskCalculatorProcessPlugin.qrc
  src/plugins/process/itkDWIBrainMaskCalculatorProcess/itkDWIBrainMaskCalculatorProcessPluginExport.h
  src/plugins/process/itkDWIBrainMaskCalculatorProcess/itkDWIBrainMaskCalculatorProcessPresenter.cpp
  src/plugins/process/itkDWIBrainMaskCalculatorProcess/itkDWIBrainMaskCalculatorProcessPresenter.h
Labels: Enhancement, Minor bug

#753 medStatusBar become threadsafe to prevent crash V4
  src/layers/legacy/medCoreLegacy/gui/commonWidgets/medStatusBar.cpp
  src/layers/legacy/medCoreLegacy/gui/commonWidgets/medStatusBar.h
Labels: Major bug

#752 medStatusBar become threadsafe to prevent crash V3.1.x
  src/layers/legacy/medCoreLegacy/gui/commonWidgets/medStatusBar.cpp
  src/layers/legacy/medCoreLegacy/gui/commonWidgets/medStatusBar.h
Labels: Major bug
