Repository medInria/medInria-public, pull requests merged in 2020-04, with the labels that each got.

#590 Feedback APHP
  src/plugins/legacy/polygonRoi/data/polygonRoi.cpp
  src/plugins/legacy/polygonRoi/data/polygonRoi.h
  src/plugins/legacy/polygonRoi/medTagRoiManager.cpp
  src/plugins/legacy/polygonRoi/medTagRoiManager.h
  src/plugins/legacy/polygonRoi/polygonEventFilter.cpp
  src/plugins/legacy/polygonRoi/polygonEventFilter.h
  src/plugins/legacy/polygonRoi/polygonRoiToolBox.cpp
  src/plugins/legacy/polygonRoi/repulsor/vtkInriaInteractorStylePolygonRepulsor.cxx
Labels: Enhancement, Major bug

#589 [Threshold] histogram and slider problems
  src/layers/legacy/medCoreLegacy/data/medAbstractImageData.h
  src/layers/legacy/medCoreLegacy/gui/toolboxes/medToolBox.cpp
  src/layers/legacy/medCoreLegacy/gui/viewContainers/medViewContainer.cpp
  src/layers/legacy/medCoreLegacy/parameters/medDoubleParameterL.cpp
  src/layers/legacy/medCoreLegacy/parameters/medDoubleParameterL.h
  src/layers/legacy/medCoreLegacy/process/medRunnableProcess.cpp
  src/layers/legacy/medCoreLegacy/views/medAbstractView.cpp
  src/layers/legacy/medCoreLegacy/views/medAbstractView.h
  src/plugins/legacy/itkFilters/itkFiltersToolBox.cpp
  src/plugins/legacy/itkFilters/itkFiltersToolBox.h
  src/plugins/legacy/itkFilters/itkMorphologicalFiltersToolBox.cpp
  src/plugins/legacy/medFilteringWorkspaceL/medFilteringWorkspaceL.cpp
  src/plugins/legacy/medVtkView/medVtkView.cpp
  src/plugins/legacy/medVtkView/medVtkView.h
Labels: Enhancement, Minor bug

#596 [Meshes] solve meshes not seen in 3D
  src/plugins/legacy/vtkDataMesh/interactors/vtkDataMeshInteractor.cpp
Labels: Critical bug

#594 [Threshold] histogram and slider problems -- master
  src/layers/legacy/medCoreLegacy/data/medAbstractImageData.h
  src/layers/legacy/medCoreLegacy/gui/toolboxes/medToolBox.cpp
  src/layers/legacy/medCoreLegacy/gui/viewContainers/medViewContainer.cpp
  src/layers/legacy/medCoreLegacy/parameters/medDoubleParameterL.cpp
  src/layers/legacy/medCoreLegacy/process/medRunnableProcess.cpp
  src/layers/legacy/medCoreLegacy/views/medAbstractView.cpp
  src/layers/legacy/medCoreLegacy/views/medAbstractView.h
  src/plugins/legacy/itkFilters/itkFiltersToolBox.cpp
  src/plugins/legacy/itkFilters/itkFiltersToolBox.h
  src/plugins/legacy/itkFilters/itkMorphologicalFiltersToolBox.cpp
  src/plugins/legacy/medFilteringWorkspaceL/medFilteringWorkspaceL.cpp
  src/plugins/legacy/medVtkView/medVtkView.cpp
  src/plugins/legacy/medVtkView/medVtkView.h
Labels: Critical bug

#598 [Variational] solve the 2 outputs problem -- master
  src/layers/legacy/medCoreLegacy/gui/toolboxes/medToolBox.cpp
  src/layers/legacy/medCoreLegacy/medMessageController.cpp
  src/plugins/legacy/variationalSegmentation/varSegToolBox.cpp
Labels: Minor bug

#600 [ViewContainer] bug with reslice/crop size, and small enhancements -- master
  src/layers/legacy/medCoreLegacy/gui/medAbstractWorkspaceLegacy.cpp
  src/layers/legacy/medCoreLegacy/gui/viewContainers/medViewContainer.cpp
  src/layers/legacy/medCoreLegacy/parameters/medDoubleParameterL.cpp
  src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImageInteractor.cpp
  src/plugins/legacy/itkFilters/itkFiltersToolBox.cpp
Labels: Major bug

#599 [ViewContainer] bug with reslice/crop size, and small enhancements
  src/layers/legacy/medCoreLegacy/gui/medAbstractWorkspaceLegacy.cpp
  src/layers/legacy/medCoreLegacy/gui/viewContainers/medViewContainer.cpp
  src/layers/legacy/medCoreLegacy/parameters/medDoubleParameterL.cpp
  src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImageInteractor.cpp
  src/plugins/legacy/itkFilters/itkFiltersToolBox.cpp
  src/plugins/legacy/itkFilters/itkFiltersToolBox.h
Labels: Major bug

#609 [medInria3.1.x] Add DICOM image series export
  src/layers/legacy/medCoreLegacy/data/medMetaDataKeys.cpp
  src/layers/legacy/medCoreLegacy/data/medMetaDataKeys.h
  src/layers/legacy/medCoreLegacy/database/medAbstractDatabaseImporter.cpp
  src/layers/legacy/medCoreLegacy/database/medDatabaseController.cpp
  src/layers/legacy/medCoreLegacy/database/medDatabaseImporter.cpp
  src/layers/legacy/medCoreLegacy/database/medDatabaseNonPersistentController.cpp
  src/layers/legacy/medCoreLegacy/database/medDatabaseNonPersistentImporter.cpp
  src/layers/legacy/medCoreLegacy/database/medDatabaseNonPersistentItem.cpp
  src/layers/legacy/medCoreLegacy/gui/database/medDatabaseView.cpp
  src/layers/legacy/medImageIO/itkDCMTKImageIO.cpp
  src/layers/legacy/medImageIO/itkDCMTKImageIO.h
  src/layers/legacy/medUtilities/medUtilities.cpp
  src/plugins/legacy/itkDataImage/itkDataImagePlugin.cpp
  src/plugins/legacy/itkDataImage/readers/itkDCMTKDataImageReader.cpp
  src/plugins/legacy/itkDataImage/writers/itkDicomDataImageWriter.cpp
  src/plugins/legacy/itkDataImage/writers/itkDicomDataImageWriter.h
Labels: Enhancement, Minor bug

#615 [Dicom] quick debug of dicom PR to compile
  src/layers/legacy/medCoreLegacy/database/medDatabaseImporter.cpp
  src/layers/legacy/medCoreLegacy/database/medDatabaseNonPersistentController.cpp
  src/layers/legacy/medCoreLegacy/database/medDatabaseReader.cpp
  src/layers/legacy/medVtkDataMeshBase/vtkMetaDataSetSequence.cxx
Labels: Critical bug

#623 [nrrd/nhrd/nrrd] debug crash opening Nordine data
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.cxx
Labels: Major bug

#625 [nrrd/nhrd/nrrd] debug crash opening Nordine data -- master
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.cxx
Labels: Major bug

#618 [Q_OS_X11] changes from Qt4->5, code was not used
  src/app/medInria/QSingleApplication/qtsingleapplication.cpp
  src/app/medInria/QSingleApplication/qtsingleapplication.h
  src/app/medInria/medSplashScreen.cpp
  src/layers/legacy/medCoreLegacy/CMakeLists.txt
  src/layers/legacy/medCoreLegacy/data/medAbstractData.cpp
  src/plugins/legacy/medVtkView/medVtkView.cpp
Labels: Minor bug

#620 [Q_OS_X11] changes from Qt4->5, code was not used -- master
  src/app/medInria/QSingleApplication/qtsingleapplication.cpp
  src/app/medInria/QSingleApplication/qtsingleapplication.h
  src/app/medInria/medSplashScreen.cpp
  src/layers/legacy/medCoreLegacy/CMakeLists.txt
  src/layers/legacy/medCoreLegacy/data/medAbstractData.cpp
  src/plugins/legacy/medVtkView/medVtkView.cpp
Labels: Minor bug

#628 Fix #583 VR not displayed without change LUT
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.cxx
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.h
Labels: Major bug

#629 Fix #583 VR not displayed without change LUT
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.cxx
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.h
Labels: Major bug

#619 add some test before dereferencing pointers
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView2D.cxx
Labels: Enhancement

#631 [FilteringWorkspaceL] remove signals duplication
  src/plugins/legacy/itkFilters/itkFiltersToolBox.cpp
  src/plugins/legacy/medFilteringWorkspaceL/medFilteringWorkspaceL.cpp
Labels: Minor bug

#632 [FilteringWorkspaceL] remove signals duplication -- master
  src/plugins/legacy/itkFilters/itkFiltersToolBox.cpp
  src/plugins/legacy/medFilteringWorkspaceL/medFilteringWorkspaceL.cpp
Labels: Minor bug

#635 [Views] remove flickering, add back thumbnails
  src/layers/legacy/medCoreLegacy/views/medAbstractView.cpp
  src/plugins/legacy/medVtkView/medVtkView.cpp
Labels: Major bug

#636 [Views] remove flickering, add back thumbnails -- master
  src/plugins/legacy/medVtkView/medVtkView.cpp
Labels: Major bug

#638 Correction of very low windowLevel images (range < 10^-2)
  src/layers/legacy/medCoreLegacy/parameters/medDoubleParameterL.cpp
  src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImageInteractor.cpp
Labels: Major bug

#637 Correction of very low windowLevel images (range < 10^-2)
  src/layers/legacy/medCoreLegacy/parameters/medDoubleParameterL.cpp
  src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImageInteractor.cpp
Labels: Major bug

#634 [Meshes] Add support for medit .mesh file format -- master
  src/layers/legacy/medVtkDataMeshBase/vtkMetaSurfaceMesh.cxx
  src/layers/legacy/medVtkDataMeshBase/vtkMetaVolumeMesh.cxx
Labels: Enhancement

#611 [medInria-3.1.x] Add support for medit .mesh file format
  src/layers/legacy/medVtkDataMeshBase/vtkMetaSurfaceMesh.cxx
  src/layers/legacy/medVtkDataMeshBase/vtkMetaVolumeMesh.cxx
Labels: Enhancement

#641 [Menu Links] Layer group 1 appears in link view properties
  src/layers/legacy/medCoreLegacy/gui/medAbstractWorkspaceLegacy.cpp
Labels: Minor bug

#642 [Menu Links] Layer group 1 appears in link view properties -- master
  src/layers/legacy/medCoreLegacy/gui/medAbstractWorkspaceLegacy.cpp
Labels: Minor bug

#646 [Ubuntu18.04] compilation ceill fabsl log10l
  src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImageInteractor.cpp
Labels: Critical bug

#648 [Ubuntu18.04] compilation ceill fabsl log10l -- master
  src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImageInteractor.cpp
Labels: Critical bug
