Repository medInria/medInria-public, pull requests merged in 2020-03, with the labels that each got.

#553 [View3D] setInputLayer forgot lines in rebase from master
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.cxx
Labels: Minor bug

#535 [Dicom import] Fix DICOM import when path contains special characters
  src/plugins/legacy/itkDataImage/readers/itkDCMTKDataImageReader.cpp
Labels: Major bug

#559 [ViewInteractor] wrong current layer creates bugs
  src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImageInteractor.cpp
  src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImageInteractor.h
Labels: Major bug

#560 [ViewInteractor] wrong current layer creates bugs - master
  src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImageInteractor.cpp
  src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImageInteractor.h
Labels: Major bug

#562 fix #554 Layer 0 deletion crashing bug (image + fibers)
  src/layers/legacy/medVtkInria/vtkImageView/vtkDataSet2DWidget.cxx
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView.cxx
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView2D.cxx
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView2D.h
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.cxx
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.h
  src/plugins/legacy/medVtkFibersData/interactors/medVtkFibersDataInteractor.cpp
  src/plugins/legacy/medVtkView/medVtkViewNavigator.cpp
  src/plugins/legacy/vtkDataMesh/interactors/vtkDataMeshInteractor.cpp
Labels: Critical bug

#572 [cstddef] remove unused include & indentation
  src/layers/legacy/medImageIO/itkGISImageIO.h
  src/layers/legacy/medImageIO/itkGISImageIOFactory.h
  src/plugins/legacy/itkDataImage/readers/itkDataImageReaderCommand.cpp
Labels: Enhancement

#564 4D load crash medInria
  src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImageInteractor.cpp
Labels: Critical bug
