Repository medInria/medInria-public, pull requests merged in 2020-06, with the labels that each got.

#716 [V3.1.x] clean medVtkInria cmake
  src/layers/legacy/medVtkInria/CMakeLists.txt
Labels: Minor bug

#717 [V4.0] clean medVtkInria cmake
  src/layers/legacy/medVtkInria/CMakeLists.txt
Labels: Minor bug

#714 [Views] Tools button debugs - data/view signals during removal -- master
  src/layers/legacy/medCoreLegacy/gui/medAbstractWorkspaceLegacy.cpp
  src/layers/legacy/medCoreLegacy/gui/medTabbedViewContainers.cpp
  src/layers/legacy/medCoreLegacy/gui/viewContainers/medViewContainer.cpp
  src/layers/legacy/medCoreLegacy/gui/viewContainers/medViewContainer.h
  src/layers/legacy/medCoreLegacy/resources/medCoreLegacy.qrc
  src/layers/legacy/medCoreLegacy/resources/pixmaps/closebutton-disabled.png
  src/plugins/legacy/medFilteringWorkspaceL/medFilteringWorkspaceL.cpp
  src/plugins/legacy/medRegistrationWorkspace/medRegistrationWorkspace.cpp
  src/plugins/legacy/medVtkView/medVtkView.cpp
Labels: Major bug

#723 [FIX] Avoid capability to save contour if there is not inside the view
  src/plugins/legacy/polygonRoi/toolboxes/contoursManagementToolBox.cpp
Labels: Major bug

#724 [V3.1.1] Paint - drawing not refresh
  src/plugins/legacy/medSegmentation/medAnnotationInteractor.cpp
Labels: Major bug

#725 [V4.0] Paint - drawing not refresh
  src/plugins/legacy/medSegmentation/medAnnotationInteractor.cpp
Labels: Major bug

#729 [Reslice] Qt AlignCenter created reslice size pb -- master
  src/layers/legacy/medCoreLegacy/gui/viewContainers/medViewContainer.cpp
Labels: Major bug

#728 [Reslice] Qt AlignCenter created reslice size pb
  src/layers/legacy/medCoreLegacy/gui/viewContainers/medViewContainer.cpp
Labels: Major bug

#731 [ReleaseNotes] last changes in release notes
  RELEASE_NOTES.txt
Labels: Discussion, Enhancement

#733 [FIX] - Add PixelDeviceRatio for Retina when MouseEvent is used
  src/plugins/legacy/medAlgorithmPaint/medAlgorithmPaintToolBox.cpp
Labels: Major bug

#737 [Various] typos and tooltips found
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView2D.cxx
  src/plugins/legacy/diffeomorphicDemons/diffeomorphicDemons.cpp
  src/plugins/legacy/medVtkView/medVtkViewNavigator.cpp
Labels: Enhancement

#739 [Q_UNUSED] remove warnings
  src/app/medInria/medLogger.cpp
  src/app/medInria/medSplashScreen.cpp
  src/layers/legacy/medCoreLegacy/data/medAbstractData.cpp
  src/layers/legacy/medCoreLegacy/database/medDataManager.cpp
  src/layers/legacy/medCoreLegacy/database/medDatabaseController.cpp
  src/layers/legacy/medCoreLegacy/database/medDatabaseModel.cpp
  src/layers/legacy/medCoreLegacy/database/medDatabaseNonPersistentImporter.cpp
  src/layers/legacy/medCoreLegacy/gui/database/medDatabaseCompactWidget.cpp
  src/layers/legacy/medCoreLegacy/gui/database/medDatabasePreview.cpp
  src/layers/legacy/medCoreLegacy/gui/database/medDatabaseView.cpp
  src/layers/legacy/medCoreLegacy/gui/lookUpTables/medClutEditor.cpp
  src/layers/legacy/medCoreLegacy/gui/medAbstractWorkspaceLegacy.cpp
  src/layers/legacy/medCoreLegacy/gui/medLinkMenu.cpp
  src/layers/legacy/medCoreLegacy/gui/medPacsSelector.cpp
  src/layers/legacy/medCoreLegacy/gui/medTabbedViewContainers.cpp
  src/layers/legacy/medCoreLegacy/gui/toolboxes/medCompositeDataSetImporterSelectorToolBox.cpp
  src/layers/legacy/medCoreLegacy/gui/toolboxes/medToolBoxHeader.cpp
  src/layers/legacy/medCoreLegacy/gui/viewContainers/medViewContainerSplitter.cpp
  src/layers/legacy/medCoreLegacy/medMessageController.cpp
  src/layers/legacy/medCoreLegacy/medViewEventFilter.cpp
  src/layers/legacy/medCoreLegacy/parameters/medVector2DParameterL.cpp
  src/layers/legacy/medCoreLegacy/parameters/medVector3DParameterL.cpp
  src/layers/legacy/medCoreLegacy/process/medAbstractProcessLegacy.cpp
  src/layers/legacy/medCoreLegacy/views/interactors/medAbstractImageViewInteractor.cpp
  src/layers/legacy/medCoreLegacy/views/medAbstractLayeredView.cpp
  src/layers/legacy/medCoreLegacy/views/medAbstractView.cpp
  src/layers/legacy/medPacs/medAbstractPacsResultDataset.cpp
  src/layers/legacy/medVtkDataMeshBase/vtkMetaDataSet.cxx
  src/layers/legacy/medVtkDataMeshBase/vtkMetaSurfaceMesh.cxx
  src/layers/legacy/medVtkInria/vtkImageView/vtkAxes2DWidget.cxx
  src/layers/legacy/medVtkInria/vtkImageView/vtkDataSet2DWidget.cxx
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView.cxx
  superbuild/projects_modules/ITK.cmake
Labels: Enhancement

#740 [medVtkFibersData] avoid crashes opening fibers in tlbx
  src/plugins/legacy/medAlgorithmPaint/medAlgorithmPaintToolBox.cpp
  src/plugins/legacy/polygonRoi/polygonRoiToolBox.cpp
  src/plugins/legacy/reformat/medCropToolBox.cpp
  src/plugins/legacy/variationalSegmentation/varSegToolBox.cpp
  src/plugins/legacy/voiCutter/voiCutterToolBox.cpp
Labels: Major bug

#743 [DICOM and medMetaDataKeys] Cherry pick 3.1.1 to master
  src/layers/legacy/medCoreLegacy/data/medMetaDataKeys.cpp
  src/layers/legacy/medCoreLegacy/data/medMetaDataKeys.h
  src/layers/legacy/medImageIO/itkDataImageReaderBase.cpp
  src/layers/legacy/medImageIO/itkDataImageReaderBase.h
  src/layers/legacy/medImageIO/itkDataImageWriterBase.cpp
  src/layers/legacy/medImageIO/itkDataImageWriterBase.h
  src/layers/legacy/medUtilities/medUtilities.cpp
  src/plugins/legacy/itkDataImage/readers/itkDCMTKDataImageReader.cpp
  src/plugins/legacy/itkDataImage/writers/itkDicomDataImageWriter.cpp
  src/plugins/legacy/itkDataImage/writers/itkDicomDataImageWriter.h
Labels: Enhancement

#745 [Warnings] override and unused warnings
  CMakeLists.txt
  src/app/medInria/medSearchToolboxDialog.cpp
  src/app/medInria/medSearchToolboxDialog.h
  src/layers/legacy/medCoreLegacy/data/medDataReaderWriter.cpp
  src/layers/legacy/medImageIO/itkDCMTKImageIO.cpp
  src/layers/legacy/medImageIO/itkDCMTKImageIO.h
  src/layers/legacy/medVtkDataMeshBase/vtkMetaDataSet.cxx
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView2D.h
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.cxx
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.h
  src/plugins/legacy/medVtkView/medVtkView.cpp
Labels: Enhancement

#746 [medMetaDataKeys] include and metadata added
  src/layers/legacy/medCoreLegacy/data/medMetaDataKeys.h
  src/layers/legacy/medImageIO/itkDataImageWriterBase.cpp
  src/plugins/legacy/itkDataImage/writers/itkDicomDataImageWriter.cpp
Labels: Major bug

#749 [medViewEventFilter] Implementation of mouse wheel events.
  src/layers/legacy/medCoreLegacy/medViewEventFilter.cpp
  src/layers/legacy/medCoreLegacy/medViewEventFilter.h
Labels: Enhancement
