Repository medInria/medInria-public, pull requests merged in 2020-05, with the labels that each got.

#658 [Browser] View, Index, dbl-click, Bookmark cleaning
  src/app/medInria/medDataSourceManager.cpp
  src/app/medInria/medDataSourceManager.h
  src/app/medInria/medFileSystemDataSource.cpp
  src/app/medInria/medFileSystemDataSource.h
  src/layers/legacy/medCoreLegacy/gui/database/medDatabaseView.cpp
  src/layers/legacy/medCoreLegacy/gui/toolboxes/medActionsToolBox.cpp
  src/layers/legacy/medCoreLegacy/gui/toolboxes/medActionsToolBox.h
  src/layers/legacy/medCoreLegacy/medAbstractDataSource.h
Labels: Major bug

#660 [Browser] View, Index, dbl-click, Bookmark cleaning -- master
  src/app/medInria/medDataSourceManager.cpp
  src/app/medInria/medDataSourceManager.h
  src/app/medInria/medFileSystemDataSource.cpp
  src/app/medInria/medFileSystemDataSource.h
  src/layers/legacy/medCoreLegacy/gui/database/medDatabaseView.cpp
  src/layers/legacy/medCoreLegacy/gui/toolboxes/medActionsToolBox.cpp
  src/layers/legacy/medCoreLegacy/gui/toolboxes/medActionsToolBox.h
  src/layers/legacy/medCoreLegacy/medAbstractDataSource.h
Labels: Major bug

#664 Apply Feedback from APHP
  src/plugins/legacy/polygonRoi/data/polygonRoi.cpp
  src/plugins/legacy/polygonRoi/medTagRoiManager.cpp
  src/plugins/legacy/polygonRoi/medTagRoiManager.h
  src/plugins/legacy/polygonRoi/polygonEventFilter.cpp
  src/plugins/legacy/polygonRoi/polygonEventFilter.h
Labels: Enhancement

#662 [itkDCMTKImageIo] remove elems warning
  src/layers/legacy/medImageIO/itkDCMTKImageIO.cpp
Labels: Enhancement

#663 [itkDCMTKImageIo] remove elems warning -- master
  src/layers/legacy/medImageIO/itkDCMTKImageIO.cpp
Labels: Enhancement

#672 solve #669 in parameters retrieving
  src/plugins/legacy/reformat/medResliceViewer.cpp
  src/plugins/legacy/reformat/resliceToolBox.cpp
Labels: Minor bug

#661 improve #326 and solve #657
  src/layers/legacy/medCoreLegacy/views/navigators/medAbstractImageViewNavigator.cpp
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView.cxx
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.cxx
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.h
  src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImageInteractor.cpp
  src/plugins/legacy/itkDataImage/navigators/medVtkViewItkDataImageNavigator.cpp
Labels: Major bug

#676 [medInria4.0] Add DICOM image series export
  src/layers/legacy/medCoreLegacy/data/medMetaDataKeys.cpp
  src/layers/legacy/medCoreLegacy/data/medMetaDataKeys.h
  src/layers/legacy/medCoreLegacy/database/medAbstractDatabaseImporter.cpp
  src/layers/legacy/medCoreLegacy/database/medDatabaseController.cpp
  src/layers/legacy/medCoreLegacy/database/medDatabaseImporter.cpp
  src/layers/legacy/medCoreLegacy/database/medDatabaseNonPersistentController.cpp
  src/layers/legacy/medCoreLegacy/database/medDatabaseNonPersistentImporter.cpp
  src/layers/legacy/medCoreLegacy/database/medDatabaseNonPersistentItem.cpp
  src/layers/legacy/medCoreLegacy/gui/database/medDatabaseView.cpp
  src/layers/legacy/medImageIO/itkDCMTKImageIO.cpp
  src/layers/legacy/medImageIO/itkDCMTKImageIO.h
  src/layers/legacy/medUtilities/medUtilities.cpp
  src/plugins/legacy/itkDataImage/itkDataImagePlugin.cpp
  src/plugins/legacy/itkDataImage/readers/itkDCMTKDataImageReader.cpp
  src/plugins/legacy/itkDataImage/writers/itkDicomDataImageWriter.cpp
  src/plugins/legacy/itkDataImage/writers/itkDicomDataImageWriter.h
Labels: Enhancement

#677 [Dicom] quick debug of dicom PR to compile -- master
  src/layers/legacy/medCoreLegacy/database/medDatabaseReader.cpp
Labels: Major bug

#685 Correction for CI windows
  src/plugins/legacy/polygonRoi/data/medTagContours.cpp
  src/plugins/legacy/polygonRoi/data/medWorldPosContours.h
  src/plugins/legacy/polygonRoi/polygonRoiToolBox.cpp
Labels: Minor bug

#689 Vtk not smart4 3.1
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.cxx
Labels: Major bug

#691 Fix #581 once min/max intensities in 3D V4.0
  src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImageInteractor.cpp
Labels: Major bug

#690 Fix #581 once min/max intensities in 3D V3.1.1
  src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImageInteractor.cpp
Labels: Major bug

#680 [medInria3.1.x]solve #669 in parameters retrieving
  src/plugins/legacy/reformat/medResliceViewer.cpp
  src/plugins/legacy/reformat/medResliceViewer.h
  src/plugins/legacy/reformat/resliceToolBox.cpp
  src/plugins/legacy/reformat/resliceToolBox.h
Labels: Major bug

#693 Put back algo name in undo redo toolbox
  src/layers/legacy/medCoreLegacy/gui/toolboxes/medRegistrationSelectorToolBox.cpp
Labels: Major bug

#698 Put back algo name in undo redo toolbox for medInria V3.1.1
  src/layers/legacy/medCoreLegacy/gui/toolboxes/medRegistrationSelectorToolBox.cpp
Labels: Major bug

#701 [LCC-LogDemons] avoid crashes (transfo, spacing, size) -- master
  src/layers/legacy/medCoreLegacy/gui/toolboxes/medRegistrationSelectorToolBox.cpp
  src/plugins/legacy/LCCLogDemons/LCCLogDemons.cpp
  src/plugins/legacy/LCCLogDemons/LCCLogDemons.h
  src/plugins/legacy/LCCLogDemons/LCCLogDemonsToolBox.cpp
  src/plugins/legacy/diffeomorphicDemons/diffeomorphicDemons.cpp
  src/plugins/legacy/diffeomorphicDemons/diffeomorphicDemonsToolBox.cpp
  src/plugins/legacy/manualRegistration/manualRegistrationToolBox.cpp
Labels: Critical bug

#700 [Registration] undo-redo current tlbx name -- master
  src/layers/legacy/medCoreLegacy/gui/toolboxes/medRegistrationSelectorToolBox.cpp
Labels: Critical bug

#702 [Registration] undo-redo current tlbx name
  src/layers/legacy/medCoreLegacy/gui/toolboxes/medRegistrationSelectorToolBox.cpp
Labels: Critical bug

#699 [LCC-LogDemons] avoid crashes (transfo, spacing, size), standardize
  src/plugins/legacy/LCCLogDemons/LCCLogDemons.cpp
  src/plugins/legacy/LCCLogDemons/LCCLogDemons.h
  src/plugins/legacy/LCCLogDemons/LCCLogDemonsToolBox.cpp
  src/plugins/legacy/diffeomorphicDemons/diffeomorphicDemons.cpp
  src/plugins/legacy/diffeomorphicDemons/diffeomorphicDemonsToolBox.cpp
  src/plugins/legacy/manualRegistration/manualRegistrationToolBox.cpp
Labels: Critical bug

#703 medLoggerRedirectWithBoost
  src/app/medInria/medLogger.cpp
  src/app/medInria/medLogger.h
Labels: Critical bug

#705 Improve log redirection for windows
  src/app/medInria/CMakeLists.txt
  src/app/medInria/medLogger.cpp
Labels: Enhancement, Minor bug

#706 Solve Glyph 2D into 3D rendering
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.cxx
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.h
Labels: Critical bug

#709 Report polygonROI plugin in medInria3.1.x
  src/app/medInria/medLogger.cpp
  src/app/medInria/resources/medInria.qrc
  src/app/medInria/resources/pixmaps/minus.png
  src/app/medInria/resources/pixmaps/plus.png
  src/layers/legacy/medCoreLegacy/data/medAbstractRoi.h
  src/layers/legacy/medCoreLegacy/gui/medRootContainer.cpp
  src/layers/legacy/medCoreLegacy/gui/medTabbedViewContainers.cpp
  src/layers/legacy/medCoreLegacy/gui/medTableWidgetChooser.cpp
  src/layers/legacy/medCoreLegacy/gui/medTableWidgetChooser.h
  src/layers/legacy/medCoreLegacy/gui/viewContainers/medViewContainer.cpp
  src/plugins/legacy/medAlgorithmPaint/medPaintBrush.cpp
  src/plugins/legacy/medAlgorithmPaint/medPaintBrush.h
  src/plugins/legacy/polygonRoi/CMakeLists.txt
  src/plugins/legacy/polygonRoi/SwitchButton.cpp
  src/plugins/legacy/polygonRoi/SwitchButton.h
  src/plugins/legacy/polygonRoi/data/medContourSharedInfo.cpp
  src/plugins/legacy/polygonRoi/data/medContourSharedInfo.h
  src/plugins/legacy/polygonRoi/data/medContours.cpp
  src/plugins/legacy/polygonRoi/data/medContours.h
  src/plugins/legacy/polygonRoi/data/medDisplayPosContours.cpp
  src/plugins/legacy/polygonRoi/data/medDisplayPosContours.h
  src/plugins/legacy/polygonRoi/data/medTagContours.cpp
  src/plugins/legacy/polygonRoi/data/medTagContours.h
  src/plugins/legacy/polygonRoi/data/medWorldPosContours.cpp
  src/plugins/legacy/polygonRoi/data/medWorldPosContours.h
  src/plugins/legacy/polygonRoi/data/polygonRoi.cpp
  src/plugins/legacy/polygonRoi/data/polygonRoi.h
  src/plugins/legacy/polygonRoi/data/vtkContourOverlayRepresentation.cxx
  src/plugins/legacy/polygonRoi/data/vtkContourOverlayRepresentation.h
  src/plugins/legacy/polygonRoi/json/specialities.json
  src/plugins/legacy/polygonRoi/medRoiManagementToolBox.cpp
  src/plugins/legacy/polygonRoi/medRoiManagementToolBox.h
  src/plugins/legacy/polygonRoi/medRoiManager.cpp
  src/plugins/legacy/polygonRoi/medRoiManager.h
  src/plugins/legacy/polygonRoi/medTagRoiManager.cpp
  src/plugins/legacy/polygonRoi/medTagRoiManager.h
  src/plugins/legacy/polygonRoi/polygonEventFilter.cpp
  src/plugins/legacy/polygonRoi/polygonEventFilter.h
  src/plugins/legacy/polygonRoi/polygonRoi.cpp
  src/plugins/legacy/polygonRoi/polygonRoi.h
  src/plugins/legacy/polygonRoi/polygonRoiPlugin.cpp
  src/plugins/legacy/polygonRoi/polygonRoiPlugin.qrc
  src/plugins/legacy/polygonRoi/polygonRoiToolBox.cpp
  src/plugins/legacy/polygonRoi/polygonRoiToolBox.h
  src/plugins/legacy/polygonRoi/readers/medContoursReader.cpp
  src/plugins/legacy/polygonRoi/readers/medContoursReader.h
  src/plugins/legacy/polygonRoi/repulsor/vtkCircleActor2D.cxx
  src/plugins/legacy/polygonRoi/repulsor/vtkCircleActor2D.h
  src/plugins/legacy/polygonRoi/repulsor/vtkInriaInteractorStylePolygonRepulsor.cxx
  src/plugins/legacy/polygonRoi/repulsor/vtkInriaInteractorStylePolygonRepulsor.h
  src/plugins/legacy/polygonRoi/toolboxes/contoursManagementToolBox.cpp
  src/plugins/legacy/polygonRoi/toolboxes/contoursManagementToolBox.h
  src/plugins/legacy/polygonRoi/toolboxes/polygonRoiToolBox.cpp
  src/plugins/legacy/polygonRoi/toolboxes/polygonRoiToolBox.h
  src/plugins/legacy/polygonRoi/vtkInriaInteractorStylePolygonRepulsor.cxx
  src/plugins/legacy/polygonRoi/writers/medContoursWriters.cpp
  src/plugins/legacy/polygonRoi/writers/medContoursWriters.h
  src/plugins/legacy/vtkDataMesh/interactors/vtkDataMeshInteractor.cpp
  superbuild/projects_modules/QtDCM.cmake
Labels: Enhancement

#713 [PolygonROI] devicePixelRatio on Qt < 5.10
  src/plugins/legacy/polygonRoi/polygonEventFilter.cpp
Labels: Major bug
