Repository medInria/medInria-public, pull requests merged in 2021-10, with the labels that each got.

#909 [PolygonROI] solve graphical/ergonomy pb and crashes - medInria4
  src/layers/legacy/medCoreLegacy/gui/medTableWidgetChooser.h
  src/plugins/legacy/polygonRoi/medTagRoiManager.cpp
  src/plugins/legacy/polygonRoi/polygonEventFilter.cpp
  src/plugins/legacy/polygonRoi/toolboxes/contoursManagementToolBox.cpp
  src/plugins/legacy/polygonRoi/toolboxes/polygonRoiToolBox.cpp
Labels: Major bug

#917 [viewContainer] background and buttons by default without data
  src/app/medInria/resources/medInria.qss
  src/layers/legacy/medCoreLegacy/gui/medAbstractWorkspaceLegacy.cpp
  src/layers/legacy/medCoreLegacy/gui/viewContainers/medViewContainer.cpp
  src/layers/legacy/medCoreLegacy/gui/viewContainers/medViewContainer.h
  src/layers/legacy/medCoreLegacy/views/medAbstractLayeredView.cpp
  src/layers/medWidgets/process/arithmetic_operation/medAbstractArithmeticOperationProcessPresenter.cpp
  src/layers/medWidgets/process/diffusion_processes/medAbstractDWIMaskingProcessPresenter.cpp
  src/layers/medWidgets/process/diffusion_processes/medAbstractDiffusionModelEstimationProcessPresenter.cpp
  src/layers/medWidgets/process/diffusion_processes/medAbstractDiffusionScalarMapsProcessPresenter.cpp
  src/layers/medWidgets/process/diffusion_processes/medAbstractTractographyProcessPresenter.cpp
  src/layers/medWidgets/process/diffusion_processes/medDiffusionModelEstimationMetaProcessPresenter.cpp
  src/layers/medWidgets/process/mask_image/medAbstractMaskImageProcessPresenter.cpp
  src/layers/medWidgets/process/morphomath_operation/medAbstractMorphomathOperationProcessPresenter.cpp
  src/layers/medWidgets/process/single_filter/medAbstractSingleFilterOperationProcessPresenter.cpp
  src/plugins/legacy/medFilteringWorkspaceL/medFilteringWorkspaceL.cpp
  src/plugins/legacy/medRegistrationWorkspace/medRegistrationWorkspace.cpp
  src/plugins/legacy/reformat/resliceToolBox.cpp
Labels: Major bug

#921 [Reslice] solve crashs after removing a data in view
  src/plugins/legacy/reformat/resliceToolBox.cpp
Labels: Major bug

#922 [Reslice] solve crashs after removing a data in view
  src/plugins/legacy/reformat/resliceToolBox.cpp
Labels: Major bug

#923 [VariationalSeg] solve crash avec 3D->2D view segmentation
  src/plugins/legacy/variationalSegmentation/varSegToolBox.cpp
  src/plugins/legacy/voiCutter/voiCutterToolBox.cpp
Labels: Major bug

#924 [VariationalSeg] solve crash avec 3D->2D view segmentation
  src/plugins/legacy/variationalSegmentation/varSegToolBox.cpp
  src/plugins/legacy/voiCutter/voiCutterToolBox.cpp
Labels: Major bug

#883 [itkDataSHImageVtkViewInteractor, itkDataTensorImageVtkViewInteractor] mem leak
  src/plugins/legacy/itkDataSHImage/interactors/itkDataSHImageVtkViewInteractor.cpp
  src/plugins/legacy/itkDataTensorImage/interactors/itkDataTensorImageVtkViewInteractor.cpp
Labels: Minor bug

#886 [medDoubleParameterL]: fix wrong (0,0) shown values when attributes has only one value for all mesh
  src/layers/legacy/medCoreLegacy/parameters/medDoubleParameterL.cpp
Labels: Major bug

#926 [ManualRegistration] avoid duplication in outputs
  src/plugins/legacy/manualRegistration/manualRegistrationToolBox.cpp
Labels: Minor bug

#927 [ManualRegistration] avoid duplication in outputs
  src/plugins/legacy/manualRegistration/manualRegistrationToolBox.cpp
Labels: Minor bug

#932 [ClutEditor] rm warning with QGraphicsItem and QObject
  src/layers/legacy/medCoreLegacy/gui/lookUpTables/medClutEditor.cpp
  src/layers/legacy/medCoreLegacy/gui/lookUpTables/medClutEditor.h
Labels: Enhancement

#937 [Icons] forgot to 4 the new time ones
  src/app/medInria/resources/icons/time_backward_step_black.svg
  src/app/medInria/resources/icons/time_backward_step_white.svg
  src/app/medInria/resources/icons/time_forward_step_black.svg
  src/app/medInria/resources/icons/time_forward_step_white.svg
Labels: Major bug
