Repository medInria/medInria-public, pull requests merged in 2022-09, with the labels that each got.

#1017 Show toolboxes even after switching workspace
  src/app/medInria/areas/browser/medBrowserArea.cpp
  src/layers/legacy/medCoreLegacy/gui/medToolBoxContainer.cpp
Labels: Major bug

#1013 Insert some useful metadatas into the database
  src/layers/legacy/medCoreLegacy/database/medAbstractDatabaseImporter.cpp
  src/layers/legacy/medCoreLegacy/database/medDatabaseImporter.cpp
  src/layers/legacy/medCoreLegacy/database/medDatabasePersistentController.cpp
  src/layers/legacy/medCoreLegacy/database/medDatabaseReader.cpp
  src/layers/legacy/medCoreLegacy/database/medLocalDbController.cpp
  src/layers/legacy/medCoreLegacy/database/medLocalDbController.h
  src/layers/legacy/medCoreLegacy/gui/database/medDatabaseMetadataItemDialog.cpp
  src/layers/legacy/medImageIO/itkDCMTKImageIO.cpp
  src/layers/legacy/medImageIO/itkDCMTKImageIO.h
  src/layers/legacy/medUtilities/medUtilities.cpp
  src/plugins/legacy/itkDataImage/readers/itkDCMTKDataImageReader.cpp
  src/plugins/legacy/itkDataImage/writers/itkDicomDataImageWriter.cpp
Labels: Minor bug

#1004 [DicomExporter]: cast image of type double, float, long and unsigned long to integer to be able to export them …
  src/plugins/legacy/itkDataImage/CMakeLists.txt
  src/plugins/legacy/itkDataImage/writers/itkDicomDataImageWriter.cpp
  src/plugins/legacy/itkDataImage/writers/itkDicomDataImageWriter.h
Labels: Enhancement

#1026 [Fedora] packaging libs in lib & lib64
  packaging/unix/medInria.sh.in
Labels: Major bug

#1006 [Attributes] some mesh fields not displayed in color in 3D
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.cxx
Labels: Major bug

#1012 [medViewContainer] allow to reset central view widgets --merge3.2
  src/layers/legacy/medCoreLegacy/gui/viewContainers/medViewContainer.cpp
  src/layers/legacy/medCoreLegacy/gui/viewContainers/medViewContainer.h
Labels: Enhancement, Major bug

#1018 [Release Notes] prepare notes for 3.3
  RELEASE_NOTES.txt
Labels: Enhancement

#989 [Selector] nothing done if same tlbx switched
  src/layers/legacy/medCoreLegacy/gui/toolboxes/medSelectorToolBox.cpp
Labels: Enhancement

#1029 [Install rules]: fix link problems between medInria and external plugins
  src/cmake/module/set_lib_install_rules.cmake
Labels: Critical bug

#1032 [Path] switch to utf8 to accept accented paths
  src/app/medInria/medMainWindow.cpp
  src/layers/legacy/medImageIO/itkDataImageReaderBase.cpp
  src/layers/legacy/medImageIO/itkDataImageWriterBase.cpp
  src/plugins/legacy/itkDataImage/readers/itkGDCMDataImageReader.cpp
  src/plugins/legacy/itkDataSHImage/readers/itkDataSHImageReader.cpp
  src/plugins/legacy/itkDataSHImage/writers/itkDataSHImageWriterBase.cpp
  src/plugins/legacy/itkDataTensorImage/readers/itkDataTensorImageReaderBase.cpp
  src/plugins/legacy/itkDataTensorImage/writers/itkDataTensorImageWriterBase.cpp
  src/plugins/legacy/medVtkFibersData/readers/medVtkFibersDataReader.cpp
  src/plugins/legacy/medVtkFibersData/writers/medVtkFibersDataWriter.cpp
  src/plugins/legacy/vtkDataMesh/readers/vtkDataMesh4DReader.cpp
  src/plugins/legacy/vtkDataMesh/writers/vtkDataMesh4DWriter.cpp
Labels: Minor bug

#1028 [Comment] small error creating warning
  src/layers/legacy/medCoreLegacy/database/medAbstractDatabaseImporter.cpp
Labels: Enhancement

#1030 [iterativeClosestPoint] rewrite ICP code, reorganize toolbox, add fiducial registration error
  src/layers/legacy/medUtilities/medUtilities.cpp
  src/layers/legacy/medUtilities/medUtilities.h
  src/plugins/legacy/iterativeClosestPoint/iterativeClosestPointProcess.cpp
  src/plugins/legacy/iterativeClosestPoint/iterativeClosestPointToolBox.cpp
  src/plugins/legacy/iterativeClosestPoint/iterativeClosestPointToolBox.h
  src/plugins/legacy/iterativeClosestPoint/medICPFilter.cxx
  src/plugins/legacy/iterativeClosestPoint/medICPFilter.h
  src/plugins/legacy/iterativeClosestPoint/vtkICPFilter.cxx
  src/plugins/legacy/iterativeClosestPoint/vtkICPFilter.h
Labels: Enhancement

#1035 [VTK] patch to compile with GCC 10 - fedora
  superbuild/patches/VTK.patch
Labels: Critical bug
