Repository medInria/medInria-public, pull requests merged in 2022-10, with the labels that each got.

#1042 [Combobox] right size with long data array name
  src/plugins/legacy/iterativeClosestPoint/iterativeClosestPointToolBox.cpp
  src/plugins/legacy/meshMapping/meshMappingToolBox.cpp
Labels: Minor bug

#1040 [PolygonRoi] enhance GUI/help + warnings at compil/opening
  src/plugins/legacy/polygonRoi/polygonLabel.cpp
  src/plugins/legacy/polygonRoi/toolboxes/defaultLabelToolBox.cpp
  src/plugins/legacy/polygonRoi/toolboxes/polygonRoiToolBox.cpp
  src/plugins/legacy/polygonRoi/toolboxes/polygonRoiToolBox.h
Labels: Enhancement

#1039 [Package] rm TmpInstall macOS code which does not package
  packaging/apple/mac_packager.sh.in
Labels: Critical bug

#1041 [Variational] GUI, applied data saved, data name, spacing error
  RELEASE_NOTES.txt
  src/plugins/legacy/variationalSegmentation/varSegToolBox.cpp
  src/plugins/legacy/variationalSegmentation/vtkLandmarkSegmentationController.cpp
Labels: Major bug

#1045 Update contributing rules in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Enhancement

#1044 Update contributing rules in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Enhancement

#1052 [medAbstractData]: add drivers capable of on offscreen rendering in generateThumbnailInGuiThread - master
  src/layers/legacy/medCoreLegacy/data/medAbstractData.cpp
Labels: Major bug

#1051 [medAbstractData]: add drivers capable of on offscreen rendering
  src/layers/legacy/medCoreLegacy/data/medAbstractData.cpp
Labels: Major bug
