Repository medInria/medInria-public, pull requests merged in 2022-03, with the labels that each got.

#972 [Paint] device ratio for cursor size --master
  src/layers/legacy/medUtilities/medUtilities.cpp
  src/layers/legacy/medUtilities/medUtilities.h
  src/plugins/legacy/medAlgorithmPaint/medAlgorithmPaintToolBox.cpp
  src/plugins/legacy/polygonRoi/polygonEventFilter.cpp
Labels: Major bug

#971 [Paint] device ratio for cursor size
  src/layers/legacy/medUtilities/medUtilities.cpp
  src/layers/legacy/medUtilities/medUtilities.h
  src/plugins/legacy/medAlgorithmPaint/medAlgorithmPaintToolBox.cpp
  src/plugins/legacy/polygonRoi/polygonEventFilter.cpp
Labels: Major bug

#976 [medPythonBaseException] fix exception message bug
  src/layers/medPython/base/error/medPythonBaseException.cpp
Labels: Minor bug

#975 Update Polygon ROI from APHP project
  src/layers/legacy/medCoreLegacy/data/medMetaDataKeys.cpp
  src/layers/legacy/medCoreLegacy/data/medMetaDataKeys.h
  src/layers/legacy/medCoreLegacy/gui/settingsWidgets/medStartupSettingsWidget.cpp
  src/layers/legacy/medUtilities/medUtilities.cpp
  src/layers/legacy/medUtilities/medUtilities.h
  src/plugins/legacy/polygonRoi/CMakeLists.txt
  src/plugins/legacy/polygonRoi/SwitchButton.cpp
  src/plugins/legacy/polygonRoi/SwitchButton.h
  src/plugins/legacy/polygonRoi/data/medContourSharedInfo.cpp
  src/plugins/legacy/polygonRoi/data/medContourSharedInfo.h
  src/plugins/legacy/polygonRoi/data/medDisplayPosContours.cpp
  src/plugins/legacy/polygonRoi/data/medDisplayPosContours.h
  src/plugins/legacy/polygonRoi/data/medLabelProperty.cpp
  src/plugins/legacy/polygonRoi/data/medLabelProperty.h
  src/plugins/legacy/polygonRoi/data/medTagContours.cpp
  src/plugins/legacy/polygonRoi/data/medTagContours.h
  src/plugins/legacy/polygonRoi/json/specialities.json
  src/plugins/legacy/polygonRoi/polygonEventFilter.cpp
  src/plugins/legacy/polygonRoi/polygonEventFilter.h
  src/plugins/legacy/polygonRoi/polygonLabel.cpp
  src/plugins/legacy/polygonRoi/polygonLabel.h
  src/plugins/legacy/polygonRoi/polygonRoiPlugin.cpp
  src/plugins/legacy/polygonRoi/toolboxes/contoursManagementToolBox.cpp
  src/plugins/legacy/polygonRoi/toolboxes/contoursManagementToolBox.h
  src/plugins/legacy/polygonRoi/toolboxes/defaultLabelToolBox.cpp
  src/plugins/legacy/polygonRoi/toolboxes/defaultLabelToolBox.h
  src/plugins/legacy/polygonRoi/toolboxes/polygonRoiToolBox.cpp
  src/plugins/legacy/polygonRoi/toolboxes/polygonRoiToolBox.h
  src/plugins/legacy/polygonRoi/toolboxes/urologyLabelToolBox.cpp
  src/plugins/legacy/polygonRoi/toolboxes/urologyLabelToolBox.h
  src/plugins/legacy/polygonRoi/viewevent/baseViewEvent.cpp
  src/plugins/legacy/polygonRoi/viewevent/baseViewEvent.h
  src/plugins/legacy/polygonRoi/viewevent/defaultViewEvent.cpp
  src/plugins/legacy/polygonRoi/viewevent/defaultViewEvent.h
  src/plugins/legacy/polygonRoi/viewevent/urologyViewEvent.cpp
  src/plugins/legacy/polygonRoi/viewevent/urologyViewEvent.h
  src/plugins/legacy/polygonRoi/viewinteractors/medMouseCrossPosition.cpp
  src/plugins/legacy/polygonRoi/viewinteractors/medMouseCrossPosition.h
  src/plugins/legacy/polygonRoi/viewinteractors/polygonRoi.cpp
  src/plugins/legacy/polygonRoi/viewinteractors/polygonRoi.h
  src/plugins/legacy/polygonRoi/viewinteractors/vtkCircleActor2D.cxx
  src/plugins/legacy/polygonRoi/viewinteractors/vtkCircleActor2D.h
  src/plugins/legacy/polygonRoi/viewinteractors/vtkContourOverlayRepresentation.cxx
  src/plugins/legacy/polygonRoi/viewinteractors/vtkContourOverlayRepresentation.h
  src/plugins/legacy/polygonRoi/viewinteractors/vtkInriaInteractorStylePolygonRepulsor.cxx
  src/plugins/legacy/polygonRoi/viewinteractors/vtkInriaInteractorStylePolygonRepulsor.h
  src/plugins/legacy/polygonRoi/writers/medContoursWriters.cpp
Labels: Enhancement

#977 [medPython] handle errors during init and plugin loading
  src/layers/medPython/base/CMakeLists.txt
  src/layers/medPython/base/core/medPythonCoreInit.cpp
  src/layers/medPython/base/medPythonUtils.cpp
  src/layers/medPython/base/medPythonUtils.h
  src/layers/medPython/tools/CMakeLists.txt
  src/layers/medPython/tools/medPythonTools.cpp
  src/layers/medPython/tools/medPythonTools.h
  src/layers/medPython/tools/python/__init__.py
  src/layers/medPython/tools/python/console.py
Labels: Enhancement

#967 [medSelectorTlbx]choose the current tlbx in selector do not run clear()
  src/layers/legacy/medCoreLegacy/gui/toolboxes/medSelectorToolBox.cpp
Labels: Minor bug
