Repository medInria/medInria-public, pull requests merged in 2023-01, with the labels that each got.

#1060 [Four-views] solve crash closing the views
  src/layers/legacy/medCoreLegacy/parameters/medViewParameterGroupL.cpp
Labels: Major bug

#1064 [Zoom] proper zoom displaying data on xy and not xyz
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView.cxx
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView.h
Labels: Major bug

#1067 [Tabs] handling of tabs: removal, switch
  src/layers/legacy/medCoreLegacy/gui/medTabbedViewContainers.cpp
  src/layers/legacy/medCoreLegacy/gui/medTabbedViewContainers.h
Labels: Major bug

#1069 [N4Bias] manage process cancel if the user wants to quit the app
  src/app/medInria/medMainWindow.cpp
  src/layers/legacy/medCoreLegacy/process/medRunnableProcess.cpp
  src/plugins/legacy/medN4BiasCorrection/medN4BiasCorrection.cpp
  src/plugins/legacy/medN4BiasCorrection/medN4BiasCorrection.h
  src/plugins/legacy/medN4BiasCorrection/medN4BiasCorrection_p.h
Labels: Minor bug

#1071 [Reslice] fix zoom error + code clarity
  src/plugins/legacy/reformat/medResliceViewer.cpp
  src/plugins/legacy/reformat/medResliceViewer.h
  src/plugins/legacy/reformat/resliceToolBox.cpp
Labels: Minor bug

#1074 [Paint] create mask before trying to paint + hide a button
  src/plugins/legacy/medAlgorithmPaint/medAlgorithmPaintToolBox.cpp
Labels: Enhancement, Minor bug

#1076 [3.3.1] release notes & version number with four view crash-fix
  CMakeLists.txt
  RELEASE_NOTES.txt
  src/CMakeLists.txt
Labels: Enhancement

#1082 Set cmake minimum version to 19 for medInria project
  CMakeLists.txt
  src/CMakeLists.txt
Labels: Enhancement

#1083 [DCM] do not corrupt exported/imported dcm with odd axis
  src/layers/legacy/medImageIO/itkDCMTKImageIO.cpp
  src/layers/legacy/medImageIO/itkDCMTKImageIO.h
Labels: Major bug

#1086 [Registration] selector toolbox empty connect
  src/layers/legacy/medCoreLegacy/gui/toolboxes/medRegistrationSelectorToolBox.cpp
Labels: Minor bug

#1079 [Git diff] solve differences between musicardio to medInria3.4
  src/layers/legacy/medCoreLegacy/CMakeLists.txt
  src/layers/legacy/medCoreLegacy/database/medDatabaseExporter.cpp
  src/layers/legacy/medCoreLegacy/database/medDatabaseImporter.cpp
  src/layers/legacy/medCoreLegacy/database/medDatabaseNonPersistentImporter.cpp
  src/layers/legacy/medCoreLegacy/database/medDatabaseNonPersistentImporter.h
  src/layers/legacy/medCoreLegacy/readers/medAbstractDataReader.cpp
  src/layers/legacy/medCoreLegacy/readers/medAbstractDataReader.h
  src/layers/legacy/medImageIO/itkDataImageWriterBase.cpp
  src/layers/legacy/medVtkDataMeshBase/vtkMetaDataSetSequence.h
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView2D.cxx
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView2D.h
  src/plugins/legacy/itkDataImage/writers/itkDicomDataImageWriter.cpp
  src/plugins/legacy/itkINRDataImageReader/CMakeLists.txt
  src/plugins/legacy/itkINRDataImageWriter/CMakeLists.txt
  src/plugins/legacy/medCompositeDataSets/CMakeLists.txt
  src/plugins/legacy/meshMapping/meshMappingToolBox.h
  src/plugins/legacy/undoRedoRegistration/CMakeLists.txt
  src/plugins/legacy/vtkDataMesh/writers/vtkDataMeshWriterBase.h
  superbuild/projects_modules/QtDCM.cmake
  superbuild/projects_modules/TTK.cmake
Labels: Enhancement

#968 [medSelectorTlbx]choose the current tlbx in selector do not run clear()
  src/layers/legacy/medCoreLegacy/gui/toolboxes/medSelectorToolBox.cpp
Labels: Minor bug

#988 [Browser] ghost toolboxes from PACS/CD tab in DB and FS tabs-master
  src/app/medInria/areas/browser/medBrowserArea.cpp
Labels: Major bug

#1005 [medDoubleParameterL] fix wrong 0/0 values if attribute has only 1 value in a mesh
  src/layers/legacy/medCoreLegacy/parameters/medDoubleParameterL.cpp
Labels: Major bug

#1007 [Mesh Visu] improvements, use vtkIdFilter and vtkGeometryFilter
  src/layers/legacy/medVtkDataMeshBase/vtkMetaVolumeMesh.cxx
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.cxx
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.h
  src/plugins/legacy/medVtkFibersData/manager/vtkFibersManager.cxx
  src/plugins/legacy/vtkDataMesh/datas/vtkDataMesh4D.cpp
  src/plugins/legacy/vtkDataMesh/interactors/vtkDataMeshInteractor.cpp
Labels: Enhancement

#1014 [CentralWidget] merge recreate default widget, and switch after data removal
  src/layers/legacy/medCoreLegacy/gui/viewContainers/medViewContainer.cpp
  src/layers/legacy/medCoreLegacy/gui/viewContainers/medViewContainer.h
  src/plugins/legacy/medFilteringWorkspaceL/medFilteringWorkspaceL.cpp
  src/plugins/legacy/medRegistrationWorkspace/medRegistrationWorkspace.cpp
Labels: Enhancement, Minor bug

#1015 [medUtilitiesITK] binarize mask to 0/1 --master
  src/layers/legacy/medUtilities/CMakeLists.txt
  src/layers/legacy/medUtilities/imageFilters.cpp
  src/layers/legacy/medUtilities/imageFilters.h
  src/layers/legacy/medUtilities/medUtilitiesITK.cpp
  src/layers/legacy/medUtilities/medUtilitiesITK.h
  src/layers/legacy/medUtilities/statsROI.cpp
  src/layers/legacy/medUtilities/statsROI.h
Labels: Major bug

#1031 [iterativeClosestPoint] rewrite ICP code, reorganize toolbox, add fiducial registration error
  src/layers/legacy/medUtilities/medUtilities.cpp
  src/layers/legacy/medUtilities/medUtilities.h
  src/plugins/legacy/iterativeClosestPoint/iterativeClosestPointProcess.cpp
  src/plugins/legacy/iterativeClosestPoint/iterativeClosestPointProcess.h
  src/plugins/legacy/iterativeClosestPoint/iterativeClosestPointToolBox.cpp
  src/plugins/legacy/iterativeClosestPoint/iterativeClosestPointToolBox.h
  src/plugins/legacy/iterativeClosestPoint/medICPFilter.cxx
  src/plugins/legacy/iterativeClosestPoint/medICPFilter.h
  src/plugins/legacy/iterativeClosestPoint/vtkICPFilter.cxx
  src/plugins/legacy/iterativeClosestPoint/vtkICPFilter.h
Labels: Enhancement

#1033 [Path] switch to utf8 to accept accented paths
  src/app/medInria/medMainWindow.cpp
  src/layers/legacy/medImageIO/itkDataImageReaderBase.cpp
  src/layers/legacy/medImageIO/itkDataImageWriterBase.cpp
  src/plugins/legacy/itkDataImage/readers/itkGDCMDataImageReader.cpp
  src/plugins/legacy/itkDataSHImage/readers/itkDataSHImageReader.cpp
  src/plugins/legacy/itkDataSHImage/writers/itkDataSHImageWriterBase.cpp
  src/plugins/legacy/itkDataTensorImage/readers/itkDataTensorImageReaderBase.cpp
  src/plugins/legacy/itkDataTensorImage/writers/itkDataTensorImageWriterBase.cpp
  src/plugins/legacy/medVtkFibersData/readers/medVtkFibersDataReader.cpp
  src/plugins/legacy/medVtkFibersData/writers/medVtkFibersDataWriter.cpp
  src/plugins/legacy/vtkDataMesh/readers/vtkDataMesh4DReader.cpp
  src/plugins/legacy/vtkDataMesh/writers/vtkDataMesh4DWriter.cpp
Labels: Minor bug

#1048 [Variational] GUI, applied data saved, data name, spacing error -- master
  RELEASE_NOTES.txt
  src/plugins/legacy/variationalSegmentation/varSegToolBox.cpp
  src/plugins/legacy/variationalSegmentation/vtkLandmarkSegmentationController.cpp
Labels: Major bug

#1057 [SearchTlbx] smaller minimum size of window
  src/app/medInria/medSearchToolboxDialog.cpp
Labels: Enhancement

#1061 [Four-views] solve crash closing the views --master
  src/layers/legacy/medCoreLegacy/parameters/medViewParameterGroupL.cpp
Labels: Major bug

#1065 [Zoom] proper zoom displaying data on xy and not xyz --master
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView.cxx
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView.h
Labels: Major bug

#1068 [Tabs] handling of tabs: removal, switch --master
  src/layers/legacy/medCoreLegacy/gui/medTabbedViewContainers.cpp
  src/layers/legacy/medCoreLegacy/gui/medTabbedViewContainers.h
Labels: Major bug

#1070 [N4Bias] manage process cancel if the user wants to quit the app
  src/app/medInria/medMainWindow.cpp
  src/layers/legacy/medCoreLegacy/process/medRunnableProcess.cpp
  src/plugins/legacy/medN4BiasCorrection/medN4BiasCorrection.cpp
  src/plugins/legacy/medN4BiasCorrection/medN4BiasCorrection.h
  src/plugins/legacy/medN4BiasCorrection/medN4BiasCorrection_p.h
Labels: Minor bug

#1072 [Reslice] fix zoom error + code clarity --master
  src/plugins/legacy/reformat/medResliceViewer.cpp
  src/plugins/legacy/reformat/medResliceViewer.h
  src/plugins/legacy/reformat/resliceToolBox.cpp
Labels: Minor bug

#1073 [Paint] create mask before trying to paint + hide a button
  src/plugins/legacy/medAlgorithmPaint/medAlgorithmPaintToolBox.cpp
Labels: Enhancement, Minor bug

#1080 [Git diff] solve differences between musicardio to medInria4
  src/layers/legacy/medCoreLegacy/CMakeLists.txt
  src/layers/legacy/medCoreLegacy/database/medDatabaseExporter.cpp
  src/layers/legacy/medCoreLegacy/database/medDatabaseImporter.cpp
  src/layers/legacy/medCoreLegacy/database/medDatabaseNonPersistentImporter.cpp
  src/layers/legacy/medCoreLegacy/database/medDatabaseNonPersistentImporter.h
  src/layers/legacy/medCoreLegacy/readers/medAbstractDataReader.cpp
  src/layers/legacy/medCoreLegacy/readers/medAbstractDataReader.h
  src/layers/legacy/medImageIO/itkDataImageWriterBase.cpp
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView2D.cxx
  src/layers/legacy/medVtkInria/vtkImageView/vtkImageView2D.h
  src/plugins/legacy/itkDataImage/writers/itkDicomDataImageWriter.cpp
  src/plugins/legacy/itkINRDataImageReader/CMakeLists.txt
  src/plugins/legacy/itkINRDataImageWriter/CMakeLists.txt
  src/plugins/legacy/medCompositeDataSets/CMakeLists.txt
  src/plugins/legacy/meshMapping/meshMappingToolBox.h
  src/plugins/legacy/undoRedoRegistration/CMakeLists.txt
  src/plugins/legacy/vtkDataMesh/writers/vtkDataMeshWriterBase.h
Labels: Enhancement

#1084 [Dicom] Fixing mirrored DICOM images and their origin
  src/layers/legacy/medImageIO/itkDCMTKImageIO.cpp
  src/layers/legacy/medImageIO/itkDCMTKImageIO.h
Labels: Major bug

#1087 [Registration] selector toolbox empty connect --master
  src/layers/legacy/medCoreLegacy/gui/toolboxes/medRegistrationSelectorToolBox.cpp
Labels: Minor bug
